Updated task 0 file

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,37 +1,22 @@
 #!/usr/bin/env bash
-# Installs Nginx with the following configurations:
-#+    Listens on port 80.
-#+    Returns a page containing "Holberton School" when queried
-#+     at the root with a curl GET request.
-# Configures /redirect_me as a "301 Moved Permanently".
-# Includes a custom 404 page containing "Ceci n'est pas une page".
+# Configure Nginx with custom HTTP header
 
-apt-get update
-apt-get install -y nginx
+# Update and install Nginx
+sudo apt update -y
+sudo apt install nginx -y
 
-mkdir /etc/nginx/html
-touch /etc/nginx/html/index.html
-echo "Hello World!" > /etc/nginx/html/index.html
-touch /etc/nginx/html/404.html
-echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
+# code to add header to display hostname
+string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;"
+sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
 
-printf %s "server {
-    listen 80;
-    listen [::]:80 default_server;
-    add_header X-Served-By $HOSTNAME;
+# Test Nginx configuration
+sudo nginx -t
 
-    root   /etc/nginx/html;
-    index  index.html index.htm;
-
-    location /redirect_me {
-        return 301 http://cuberule.com/;
-    }
-
-    error_page 404 /404.html;
-    location /404 {
-      root /etc/nginx/html;
-      internal;
-    }
-}" > /etc/nginx/sites-available/default
-
-service nginx restart
+# If the test is successful, restart Nginx
+if [ $? -eq 0 ]; then
+    sudo service nginx restart
+    echo "Nginx configuration updated and restarted successfully."
+else
+    echo "Nginx configuration test failed. Please check the configuration."
+    exit 1
+fi
